# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: 0.3.5
_src_path: gh:algorandfoundation/algokit-typescript-template
author_email: ayushcrudani@gmail.com
author_name: ayush-rudani
contract_name: percival_sc
preset_name: starter
project_name: Percival-contracts

